create a docker build image workflow
mattermost/mattermost-pgbouncer-config-reload pull request #1
Opened 2023-09-13 11:47 UTC by angeloskyratzakos

#### Summary
create a docker build image workflow

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-6225

2023-09-13 11:50 UTC, toninis requested changes
LGTM 🚀  Just some minor comments

2023-09-13 11:50 UTC, toninis commented on .github/workflows/image-build.yaml
> +    if: github.repository_owner == 'mattermost' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
This is not needed

2023-09-13 11:50 UTC, toninis commented on .github/workflows/image-build.yaml
> +          password: ${{ secrets.DOCKERHUB_DEV_TOKEN }}
```suggestion
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```

2023-09-13 11:50 UTC, toninis commented on .github/workflows/image-build.yaml
> +          REPO_NAME: ${{ github.event.repository.name }}
These are not needed

2023-09-13 11:50 UTC, toninis commented on .github/workflows/image-build.yaml
> +          export DOCKER_CLI_EXPERIMENTAL=enabled
This is also not needed

2023-09-13 13:52 UTC, toninis commented on .github/workflows/image-build.yaml
> +      - name: cd/Login to Docker Hub
```suggestion
      - name: checkout-project
         uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: cd/Login to Docker Hub
```

2023-09-14 09:10 UTC, stafot approved these changes
LGTM

2023-09-14 09:10 UTC, angeloskyratzakos commented
@toninis the docker credentials are failing, do you have any idea why is that?

2023-09-14 09:13 UTC, toninis commented
> @toninis the docker credentials are failing, do you have any idea why is that?

Should be ok . Secrets where not propagated properly :)

2023-09-14 13:30 UTC, merged